### ISSUE TITLE
seaborn.tsplot deprecado en notebook 02_Matplotlib

### ISSUE THREAD

**Issue by jmloyola** [Grupo-de-modelado-probabilista/python_eda#5]
La notebook 02_Matplotlib hace uso de `seaborn.tsplot` que está deprecado.
Se puede utilizar `seaborn.lineplot`, pero no se cómo lo generaba orginalmente tsplot para replicarlo.

Estas dos opciones tengo:
![imagen](https://user-images.githubusercontent.com/2133361/181611526-fe9e0997-8436-48c1-8c25-4cc07693ea88.png)

¿Cual te parece mejor?

**Comment by aloctavodia** [comment]
La de la izquierda.
